docs/setting-up-a-new-node.md

Add section about setting up binary as a service

---

docs/setting-up-a-new-node.md

Added additional information that would have helped me.

Updating guidance for setting up a new node.

---

docker/single_image_testnet/gen_node_configs.sh

Add vesting accounts for cheqd-testnet image

---

app/prefix.go
docker/single_image_testnet/gen_node_configs.sh

Move to prefix cheqd

---

docker/cheqd_node/Dockerfile

Remove VOLUME cmd

---

docker/cheqd_node/Dockerfile

Fix version for starport

---

app/app.go

Add upgrade handler for future proposal upgrade_to_0.3.0

---

build_tools/postinst
docs/deb-package-overview.md
docs/setting-up-a-new-node.md

Get rid of symlinks and add ability to change HOME directory

---

docs/swagger.yaml

Add swagger docs

---

build_tools/postinst

Add chown for directories in .deb

---

docker/cheqd_node.md
docker/cheqd_node/Dockerfile
docker/cheqd_node/node-runner.sh

* Disabled logging during secrets management
* Added `CHEQD_HOME_DIR` build arg

Docker improvements

---

.github/workflows/node-ci-pull-request.yml
.github/workflows/node-ci-push.yml

Change split-workflow branch to main

---

Makefile

Add --tag for releases

---

cmd/cheqd-noded/cmd/debug_extensions.go
tests/e2e-bash/tests/common.sh
tests/e2e-bash/tests/test_create_did_with_invalid_pubkey.sh
x/cheqd/keeper/verify.go

TODO: Redirect to main when the base PR is merged

DEV-1039 Fix panic in case of invalid key format

---

x/cheqd/keeper/msg_server_update_did.go
x/cheqd/tests/constants.go
x/cheqd/tests/setup.go
x/cheqd/tests/signature_verification_test.go
x/cheqd/tests/update_did_test.go
x/cheqd/tests/utils.go
x/cheqd/types/common_key_value_pair.go
x/cheqd/types/did_did.go
x/cheqd/types/did_service.go
x/cheqd/types/did_verification_method.go
x/cheqd/types/tx_msg_create_did.go
x/cheqd/types/tx_msg_create_did_payload.go
x/cheqd/types/tx_msg_update_did.go
x/cheqd/types/tx_msg_update_did_payload.go
x/cheqd/types/tx_sign_info.go
x/cheqd/types/tx_sign_ingo_test.go

Signed-off-by: Andrew Nikitin <andrew.nikitin@cheqd.io>

[DEV-705] The latest changes around UpdateDid functionality

---

docs/setup-and-configure/debian/deb-package-upgrade.md

Signed-off-by: Andrew Nikitin <andrew.nikitin@cheqd.io>

[DEV-1171] Add additional instruction for updating from 0.4.x version

---

.github/workflows/release.yml

fix: Get rid of debian package for release

---

installer/installer.py
scripts/state-sync.sh

fix(installer): Change snapshot URL calculating logic

---

docker/localnet/docker-compose.yml

Signed-off-by: Andrew Nikitin <andrew.nikitin@cheqd.io>

chore: Fix localnet running

---

.github/workflows/dispatch.yml
go.mod
go.sum

* Added support for ledger nano s plus
* Added support for ledger nano s plus
* Update go.sum
* Update go.mod
Co-authored-by: Ankur Banerjee <ankurdotb@users.noreply.github.com>
Co-authored-by: Alexander Kolesov <alexandr.kolesov@cheqd.io>

fix: Add support for Ledger nano

---

app/migrations/helpers/constant.go
app/migrations/helpers/protobuf.go
app/migrations/helpers/protobuf_test.go

Fix for converting old time to timestamp

fix: Fix for converting old time to timestamp (#511)

---

.github/workflows/dispatch.yml
go.mod
go.sum
go.work.sum
package-lock.json

- Backports Barberry vulnerability patch to relevant cheqd fork of Cosmos SDK.

fix(security): "Barberry" vulnerability patch [DEV-2775]

---

.github/workflows/test.yml
ante/fee.go
ante/fee_test.go
app/app.go
app/upgrades/v3/const.go
tests/integration/cli/config.go
tests/integration/cli/query.go
tests/integration/cli/tx.go
tests/integration/cli_defi_test.go
x/did/types/denom.go

- Adds fee offset guard.
- Enhances antehandler unit test cases, including an update to realistic values (like-to-like with live networks).
- Augments integration test suite.

fix: Added embedded fee offset calculation on feecheck + realistic unit test assurance
